-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.allocation_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['start_allocation'::character varying, 'end_allocation'::character varying, 'downtime_start'::character varying, 'downtime_end'::character varying, 'correction'::character varying, 'extension_attach'::character varying, 'extension_detach'::character varying, 'transport_start'::character varying, 'transport_arrival'::character varying, 'request_allocation'::character varying, 'confirm_allocation'::character varying, 'material_entry'::character varying, 'product_exit'::character varying, 'refueling'::character varying, 'monitoring'::character varying, 'request_maintenance'::character varying]::text[])),
  machine_id uuid,
  site_id uuid,
  extension_id uuid,
  event_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  downtime_reason character varying,
  downtime_description text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  corrects_event_id uuid,
  correction_description text,
  created_by uuid NOT NULL,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  supplier_id uuid,
  construction_type character varying CHECK (construction_type::text = ANY (ARRAY['lot'::character varying, 'building'::character varying]::text[])),
  lot_building_number character varying,
  has_refueling boolean NOT NULL DEFAULT false,
  machine_type_id uuid,
  sharepoint_links jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT allocation_events_pkey PRIMARY KEY (id),
  CONSTRAINT allocation_events_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT allocation_events_corrects_event_id_fkey FOREIGN KEY (corrects_event_id) REFERENCES public.allocation_events(id),
  CONSTRAINT allocation_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT allocation_events_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(id),
  CONSTRAINT allocation_events_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT allocation_events_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT allocation_events_machine_type_id_fkey FOREIGN KEY (machine_type_id) REFERENCES public.machine_types(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entidade character varying NOT NULL,
  entidade_id uuid NOT NULL,
  acao character varying NOT NULL CHECK (acao::text = ANY (ARRAY['insert'::character varying, 'update'::character varying, 'delete'::character varying]::text[])),
  dados_antes jsonb,
  dados_depois jsonb,
  usuario_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.users(id)
);
CREATE TABLE public.login_attempts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ip_address character varying NOT NULL,
  attempts integer DEFAULT 0,
  blocked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT login_attempts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.machine_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nome character varying NOT NULL UNIQUE,
  icon character varying,
  created_at timestamp with time zone DEFAULT now(),
  is_attachment boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT machine_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.machines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  unit_number character varying NOT NULL UNIQUE,
  machine_type_id uuid NOT NULL,
  ownership_type character varying NOT NULL CHECK (ownership_type::text = ANY (ARRAY['owned'::character varying, 'rented'::character varying]::text[])),
  supplier_id uuid,
  billing_type character varying CHECK (billing_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying]::text[])),
  daily_rate numeric,
  weekly_rate numeric,
  monthly_rate numeric,
  current_site_id uuid,
  status character varying DEFAULT 'available'::character varying CHECK (status::text = ANY (ARRAY['available'::character varying, 'allocated'::character varying, 'maintenance'::character varying, 'inactive'::character varying, 'in_transit'::character varying]::text[])),
  notas text,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT machines_pkey PRIMARY KEY (id),
  CONSTRAINT machines_machine_type_id_fkey FOREIGN KEY (machine_type_id) REFERENCES public.machine_types(id),
  CONSTRAINT machines_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT machines_current_site_id_fkey FOREIGN KEY (current_site_id) REFERENCES public.sites(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid,
  root_type character varying NOT NULL,
  titulo text NOT NULL,
  mensagem text NOT NULL,
  trigger_date timestamp with time zone NOT NULL,
  archived_by jsonb DEFAULT '[]'::jsonb,
  viewed_by jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.allocation_events(id)
);
CREATE TABLE public.refueling_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  site_id uuid NOT NULL,
  machine_id uuid NOT NULL,
  fuel_supplier_id uuid,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  time_of_day time without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT refueling_templates_pkey PRIMARY KEY (id),
  CONSTRAINT refueling_templates_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(id),
  CONSTRAINT refueling_templates_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(id),
  CONSTRAINT refueling_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.sites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  geocoding_confidence numeric,
  place_type character varying,
  city character varying,
  state character varying,
  country character varying DEFAULT 'Brasil'::character varying,
  ativo boolean DEFAULT true,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_headquarters boolean DEFAULT false,
  CONSTRAINT sites_pkey PRIMARY KEY (id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nome character varying NOT NULL UNIQUE,
  email character varying,
  telefone character varying,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  supplier_type character varying DEFAULT 'rental'::character varying CHECK (supplier_type::text = ANY (ARRAY['rental'::character varying, 'maintenance'::character varying, 'both'::character varying, 'fuel'::character varying]::text[])),
  archived boolean DEFAULT false,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nome character varying NOT NULL,
  email character varying UNIQUE,
  pin_hash character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying, 'dev'::character varying, 'operador'::character varying, 'fornecedor'::character varying]::text[])),
  can_view_dashboard boolean DEFAULT false,
  can_view_map boolean DEFAULT false,
  can_manage_sites boolean DEFAULT false,
  can_manage_machines boolean DEFAULT false,
  can_register_events boolean DEFAULT false,
  can_approve_events boolean DEFAULT false,
  can_view_financial boolean DEFAULT false,
  can_manage_suppliers boolean DEFAULT false,
  can_manage_users boolean DEFAULT false,
  can_view_logs boolean DEFAULT false,
  supplier_id uuid,
  validado boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_users_supplier FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);